version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /**/*
cache:
  paths:
    - node_modules/**/*