version: 1

phases:
  pre-build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Start Building
      - node app
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /**/*
cache:
  paths:
    - node_modules/**/*